/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace EscrowManager {
      
    export type ListingStruct = {id: BigNumberish, seller: AddressLike, price: BigNumberish, metadataRef: string, active: boolean}

    export type ListingStructOutput = [id: bigint, seller: string, price: bigint, metadataRef: string, active: boolean] & {id: bigint, seller: string, price: bigint, metadataRef: string, active: boolean }
  

    export type OrderStruct = {id: BigNumberish, listingId: BigNumberish, buyer: AddressLike, seller: AddressLike, amount: BigNumberish, status: BigNumberish, deadline: BigNumberish}

    export type OrderStructOutput = [id: bigint, listingId: bigint, buyer: string, seller: string, amount: bigint, status: bigint, deadline: bigint] & {id: bigint, listingId: bigint, buyer: string, seller: string, amount: bigint, status: bigint, deadline: bigint }
  
    }

  export interface EscrowManagerInterface extends Interface {
    getFunction(nameOrSignature: "TIMEOUT_DURATION" | "buy" | "cancelListing" | "claimTimeout" | "confirmReceipt" | "contentCount" | "createListing" | "getListing" | "getOrder" | "getPublicKey" | "listingCount" | "listings" | "orderCount" | "orders" | "pendingWithdrawals" | "publicKeys" | "registerPublicKey" | "sendContent" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ContentSent" | "ListingCancelled" | "ListingCreated" | "OrderConfirmed" | "OrderCreated" | "OrderTimeoutClaimed" | "PublicKeyRegistered" | "Withdrawal"): EventFragment;

    encodeFunctionData(functionFragment: 'TIMEOUT_DURATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'buy', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelListing', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimTimeout', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'confirmReceipt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'contentCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'createListing', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'getListing', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getOrder', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPublicKey', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'listingCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'listings', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'orderCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'orders', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pendingWithdrawals', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'publicKeys', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registerPublicKey', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'sendContent', values: [AddressLike, string]): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'TIMEOUT_DURATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimTimeout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmReceipt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contentCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPublicKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listingCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'orderCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'orders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingWithdrawals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'publicKeys', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerPublicKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sendContent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace ContentSentEvent {
      export type InputTuple = [contentId: BigNumberish, sender: AddressLike, receiver: AddressLike, contentType: string];
      export type OutputTuple = [contentId: bigint, sender: string, receiver: string, contentType: string];
      export interface OutputObject {contentId: bigint, sender: string, receiver: string, contentType: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ListingCancelledEvent {
      export type InputTuple = [listingId: BigNumberish];
      export type OutputTuple = [listingId: bigint];
      export interface OutputObject {listingId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ListingCreatedEvent {
      export type InputTuple = [listingId: BigNumberish, seller: AddressLike, price: BigNumberish, metadataRef: string];
      export type OutputTuple = [listingId: bigint, seller: string, price: bigint, metadataRef: string];
      export interface OutputObject {listingId: bigint, seller: string, price: bigint, metadataRef: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderConfirmedEvent {
      export type InputTuple = [orderId: BigNumberish];
      export type OutputTuple = [orderId: bigint];
      export interface OutputObject {orderId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderCreatedEvent {
      export type InputTuple = [orderId: BigNumberish, listingId: BigNumberish, buyer: AddressLike, seller: AddressLike, amount: BigNumberish, deadline: BigNumberish];
      export type OutputTuple = [orderId: bigint, listingId: bigint, buyer: string, seller: string, amount: bigint, deadline: bigint];
      export interface OutputObject {orderId: bigint, listingId: bigint, buyer: string, seller: string, amount: bigint, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderTimeoutClaimedEvent {
      export type InputTuple = [orderId: BigNumberish];
      export type OutputTuple = [orderId: bigint];
      export interface OutputObject {orderId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PublicKeyRegisteredEvent {
      export type InputTuple = [account: AddressLike, publicKey: BytesLike];
      export type OutputTuple = [account: string, publicKey: string];
      export interface OutputObject {account: string, publicKey: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawalEvent {
      export type InputTuple = [account: AddressLike, amount: BigNumberish];
      export type OutputTuple = [account: string, amount: bigint];
      export interface OutputObject {account: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EscrowManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): EscrowManager;
    waitForDeployment(): Promise<this>;

    interface: EscrowManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    TIMEOUT_DURATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    buy: TypedContractMethod<
      [listingId: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    cancelListing: TypedContractMethod<
      [listingId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claimTimeout: TypedContractMethod<
      [orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    confirmReceipt: TypedContractMethod<
      [orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    contentCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    createListing: TypedContractMethod<
      [price: BigNumberish, metadataRef: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    getListing: TypedContractMethod<
      [listingId: BigNumberish, ],
      [EscrowManager.ListingStructOutput],
      'view'
    >
    

    
    getOrder: TypedContractMethod<
      [orderId: BigNumberish, ],
      [EscrowManager.OrderStructOutput],
      'view'
    >
    

    
    getPublicKey: TypedContractMethod<
      [account: AddressLike, ],
      [string],
      'view'
    >
    

    
    listingCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    listings: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, string, boolean] & {id: bigint, seller: string, price: bigint, metadataRef: string, active: boolean }],
      'view'
    >
    

    
    orderCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    orders: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, string, string, bigint, bigint, bigint] & {id: bigint, listingId: bigint, buyer: string, seller: string, amount: bigint, status: bigint, deadline: bigint }],
      'view'
    >
    

    
    pendingWithdrawals: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    publicKeys: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    registerPublicKey: TypedContractMethod<
      [publicKey: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    sendContent: TypedContractMethod<
      [receiver: AddressLike, contentType: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'TIMEOUT_DURATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buy'): TypedContractMethod<
      [listingId: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'cancelListing'): TypedContractMethod<
      [listingId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimTimeout'): TypedContractMethod<
      [orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'confirmReceipt'): TypedContractMethod<
      [orderId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'contentCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createListing'): TypedContractMethod<
      [price: BigNumberish, metadataRef: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getListing'): TypedContractMethod<
      [listingId: BigNumberish, ],
      [EscrowManager.ListingStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getOrder'): TypedContractMethod<
      [orderId: BigNumberish, ],
      [EscrowManager.OrderStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPublicKey'): TypedContractMethod<
      [account: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'listingCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'listings'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, string, boolean] & {id: bigint, seller: string, price: bigint, metadataRef: string, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'orderCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'orders'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, string, string, bigint, bigint, bigint] & {id: bigint, listingId: bigint, buyer: string, seller: string, amount: bigint, status: bigint, deadline: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'pendingWithdrawals'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'publicKeys'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerPublicKey'): TypedContractMethod<
      [publicKey: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sendContent'): TypedContractMethod<
      [receiver: AddressLike, contentType: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ContentSent'): TypedContractEvent<ContentSentEvent.InputTuple, ContentSentEvent.OutputTuple, ContentSentEvent.OutputObject>;
getEvent(key: 'ListingCancelled'): TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;
getEvent(key: 'ListingCreated'): TypedContractEvent<ListingCreatedEvent.InputTuple, ListingCreatedEvent.OutputTuple, ListingCreatedEvent.OutputObject>;
getEvent(key: 'OrderConfirmed'): TypedContractEvent<OrderConfirmedEvent.InputTuple, OrderConfirmedEvent.OutputTuple, OrderConfirmedEvent.OutputObject>;
getEvent(key: 'OrderCreated'): TypedContractEvent<OrderCreatedEvent.InputTuple, OrderCreatedEvent.OutputTuple, OrderCreatedEvent.OutputObject>;
getEvent(key: 'OrderTimeoutClaimed'): TypedContractEvent<OrderTimeoutClaimedEvent.InputTuple, OrderTimeoutClaimedEvent.OutputTuple, OrderTimeoutClaimedEvent.OutputObject>;
getEvent(key: 'PublicKeyRegistered'): TypedContractEvent<PublicKeyRegisteredEvent.InputTuple, PublicKeyRegisteredEvent.OutputTuple, PublicKeyRegisteredEvent.OutputObject>;
getEvent(key: 'Withdrawal'): TypedContractEvent<WithdrawalEvent.InputTuple, WithdrawalEvent.OutputTuple, WithdrawalEvent.OutputObject>;

    filters: {
      
      'ContentSent(uint256,address,address,string)': TypedContractEvent<ContentSentEvent.InputTuple, ContentSentEvent.OutputTuple, ContentSentEvent.OutputObject>;
      ContentSent: TypedContractEvent<ContentSentEvent.InputTuple, ContentSentEvent.OutputTuple, ContentSentEvent.OutputObject>;
    

      'ListingCancelled(uint256)': TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;
      ListingCancelled: TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;
    

      'ListingCreated(uint256,address,uint256,string)': TypedContractEvent<ListingCreatedEvent.InputTuple, ListingCreatedEvent.OutputTuple, ListingCreatedEvent.OutputObject>;
      ListingCreated: TypedContractEvent<ListingCreatedEvent.InputTuple, ListingCreatedEvent.OutputTuple, ListingCreatedEvent.OutputObject>;
    

      'OrderConfirmed(uint256)': TypedContractEvent<OrderConfirmedEvent.InputTuple, OrderConfirmedEvent.OutputTuple, OrderConfirmedEvent.OutputObject>;
      OrderConfirmed: TypedContractEvent<OrderConfirmedEvent.InputTuple, OrderConfirmedEvent.OutputTuple, OrderConfirmedEvent.OutputObject>;
    

      'OrderCreated(uint256,uint256,address,address,uint256,uint256)': TypedContractEvent<OrderCreatedEvent.InputTuple, OrderCreatedEvent.OutputTuple, OrderCreatedEvent.OutputObject>;
      OrderCreated: TypedContractEvent<OrderCreatedEvent.InputTuple, OrderCreatedEvent.OutputTuple, OrderCreatedEvent.OutputObject>;
    

      'OrderTimeoutClaimed(uint256)': TypedContractEvent<OrderTimeoutClaimedEvent.InputTuple, OrderTimeoutClaimedEvent.OutputTuple, OrderTimeoutClaimedEvent.OutputObject>;
      OrderTimeoutClaimed: TypedContractEvent<OrderTimeoutClaimedEvent.InputTuple, OrderTimeoutClaimedEvent.OutputTuple, OrderTimeoutClaimedEvent.OutputObject>;
    

      'PublicKeyRegistered(address,bytes)': TypedContractEvent<PublicKeyRegisteredEvent.InputTuple, PublicKeyRegisteredEvent.OutputTuple, PublicKeyRegisteredEvent.OutputObject>;
      PublicKeyRegistered: TypedContractEvent<PublicKeyRegisteredEvent.InputTuple, PublicKeyRegisteredEvent.OutputTuple, PublicKeyRegisteredEvent.OutputObject>;
    

      'Withdrawal(address,uint256)': TypedContractEvent<WithdrawalEvent.InputTuple, WithdrawalEvent.OutputTuple, WithdrawalEvent.OutputObject>;
      Withdrawal: TypedContractEvent<WithdrawalEvent.InputTuple, WithdrawalEvent.OutputTuple, WithdrawalEvent.OutputObject>;
    
    };
  }